### ISSUE TITLE
LWJGL 3 support.

### ISSUE THREAD

**Issue by dustContributor** [nifty-gui/nifty-gui#304]
Hi! LWJGL 3 has been released. Most (if not all) the GLxx.xx calls are exactly the same but there are a few things here and there that changed (GLU is gone IIRC).

**Comment by bgroenks96** [comment]
Is this a feature request? Or does using LWJGL 3 with Nifty break something?

**Comment by mkaring** [comment]
I think LWJGL 3 has a completely new API. So I do not think it will work at all. Also LWJGL 3 is still under heavy development. I suggest waiting a little until creating a renderer for this new version.

**Comment by dustContributor** [comment]
Actually you should ask Spasi about it. I'm pretty sure the API calls NiftyGUI deals with (ie, plain OGL calls, no context nor windows creation) are stable and the same as LWJGL 2. Thing is that GLU is definitively out, so any GLU calls (like error string ones) won't work.

**Comment by dustContributor** [comment]
So a heads up. I'm trying to set up Nifty with LWJGL3 (like, right now). So far LwjglInputSystem completely fails because all of that input stuff has been removed in LWJGL3 (now there aren't Mouse/Keyboard/Display classes anymore, but GLFW's instead).

**Comment by dustContributor** [comment]
Ohh and now OpenGL stuff too. GL20.glGetShader doesnt exists in LWJGL3, you got glGetShaderi or glGetShaderiv, since Spasi removed the whole "postfix avoiding" thing when passing buffers, so all calls have postfixes like 'fv'.

So far I'm getting issues in LwjglCoreGL for:
- GL20.glGetProgram, should be GL20.glGetProgramiv
- GL20.glGetShader, should be  GL20.glGetShaderiv
- GL20.glUniform1, should be GL20.glUniform1fv
- GL20.glUniformMatrix4, should be GL20.glUniformMatrix4fv.
- GL11.glGetInteger, should be GL11.glGetIntegerv

**Comment by dustContributor** [comment]
And now NoClassDefFoundError inside 'LwjglMouseCursor' constructor, because org.lwjgl.LWJGLException doesn't exists. Prolly other methods would fail too because 'Mouse' class isn't there anymore and 'Cursor' either.

**Comment by bgroenks96** [comment]
Sounds like we will definitely be needing a new renderer then.

I probably _shouldn't_ work on this since I generally deal with JOGL stuff, and I haven't used LWJGL much. But if you want to go ahead and clone the LWJGL2 module and start hacking away at a LWJGL3 port, that would be super helpful! And I can definitely pull in your changes.

Or @mkaring or @void256 could possibly work on it, but Nifty 2.0 development is under-way... so I don't know if they have time.

**Comment by dustContributor** [comment]
I am not terribly sure how to implement the input system part. Renderer is just a matter if changing a few call names, but input is completely different since now it works through GLFW.

GLFW works with callbacks. Instead of LWJGL doing the input buffering for you through static globally accessible classes, GLFW depends on a callback you pass to it that it will call on mouse/keyboard events. Moreover it only supports _one_ callback, ie, NiftyGUI can't just set the callback to whatever it needs because it will overwrite the main application's callback. 

And now that I think of it, not sure if sound systems that depend on LWJGL's OpenAL bindings will work either.

**Comment by void256** [comment]
I'd vote for a LWJGL3 renderer besides the old lwjgl renderer project then!

I've not looked into any LWJGL3 stuff but I've always been a LWJGL fan and would like to see support for that in Nifty too.

About the input event processing I think it should be clear to anyone that wants to use Nifty and LWJGL3/GLFW that Nifty needs access to input events too. Therefore I don't see a real problem with the callbacks.

We could support two modes of operation:
1. You tell Nifty to use the GLFW callbacks and so Nifty gets them first and makes any unprocessed events available to user code - similar to the way the current LWJGL inputsystem works iirc
2. or you give Nifty the events you want it to process by calling a method on the InputSystem, the InputSystems stores them internally and when later being called by Nifty to process input events it forwards all the stored events to Nifty.

Without having looked further into it yet, I guess we could equally support both methods and let the user decide how to best integrate input processing into his application :smile:

**Comment by dustContributor** [comment]
Second way is what I'd prefer, otherwise it screws right through the way I set up input handling...

In any case, I think the callback could be hijacked. GLFW's function to set the callback returns the previous one, so I think Nifty's callback could be appended to the existing one if needed (ie, create a new anonymous class that handles nifty stuff and calls the previous callback).

Then again that's easy to break, if the user creates Nifty's input system first and then creates its own callback, Nifty's callback would be overwritten. Although I wouldn't have any particular problem with that as long as its documented so its known that you have to init your own callback first.

**Comment by gustav3d** [comment]
any progress ? :)

**Comment by bgroenks96** [comment]
@dustContributor @void256 @mkaring 

Do we have anyone currently working on this?

**Comment by dustContributor** [comment]
@bgroenks96 

Not me, sorry.

**Comment by bgroenks96** [comment]
I'm not super familiar with LWJGL and especially not LWJGL3... so we need a brave, LWJGL savvy volunteer for this.

**Comment by marko-lazic** [comment]
Someone have to do it.

**Comment by bgroenks96** [comment]
I just finished a WIP commit on my fork. I have all of the rendering stuff ported (that was pretty easy), but the LWJGL3 input system is completely different.

As such, the Nifty LwjglInputSystem needs a complete overhaul. I don't have time to learn their new API right now... so I'm afraid we will have to keep putting this on hold.

That is, unless someone wants to pick up where I left off :wink: 
https://github.com/bgroenks96/nifty-gui/tree/lwjgl3-renderer

**Comment by marko-lazic** [comment]
Maybe this can help:
https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.3-Input-handling-with-GLFW
I believe that it will not change anymore again until Java and GLFW are thing.

**Comment by biskiti** [comment]
Hi guys, is there any progress?

**Comment by dustContributor** [comment]
I decided I'd work on an editor first rather than the game UI, and I'm using JavaFX for that, so I haven't looked into this any further.

**Comment by bgroenks96** [comment]
@biskiti 

Now that you reminded me, I went ahead and finished porting the LWJGL backend to LWJGL3. Everything should (theoretically) work. I have not yet rewritten the example runner, however, so it hasn't yet been tested :cold_sweat: 

If you get a chance, please head over to the [feature branch](https://github.com/bgroenks96/nifty-gui/tree/lwjgl3-renderer) on my fork, clone it, build it, and let me know if works in a LWJGL3 application.

You can build it as you would normally build nifty:

```
mvn clean install
```

in the main directory. Use version 1.4.3-SNAPSHOT for nifty main and nifty-renderer-lwjgl3.

**Comment by biskiti** [comment]
Hi,

skiping pauls sound system and examples, build was done sucessfully

I'll do some tests.

Thanks a lot

**Comment by KillingSpark** [comment]
Hi i've been working on a very simple GUI that works with LWJGL3. Nothing special but if you want something easy and clean try it out. https://github.com/KillingSpark/lwjglGUI

**Comment by bgroenks96** [comment]
@KillingSpark I do hope you aren't using one of our issue threads as a medium for advertising your own project...? That would not be cool.

If you mean try it out with Nifty, your project would need to be already using NIftyGUI (preferably the LWJGL 2.x backend) to work for testing the new LWJGL3 renderer. I'm interested in hearing from people using the current LWJGL renderer and whether or not dropping in LWJGL3 works for them.
